version: "3.9"
services:
  backend:
    build: ./server
    container_name: spotify-backend
    ports:
      - "5000:5000"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    restart: always

  frontend:
    build: ./frontend
    container_name: spotify-frontend
    ports:
      - "8083:3000" # Map frontend to localhost:8083
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    restart: always
